#- platform: nmap_tracker
#  hosts: 
#    - 192.168.0.200-209
#    - 192.168.0.233
#  track_new_devices: no
# Life360
- platform: life360
  username: !secret life360_username
  password: !secret life360_password
  add_zones: all
  driving_speed: 18
  filename: life360.conf
  home_place: Home
  interval_seconds: 10
  max_gps_accuracy: 200
  prefix: life360
  show_as_state: driving, moving, places