- platform: google_travel_time
  name: Michelle To Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.michelle_g7
  destination: zone.home
  scan_interval: 86400
- platform: google_travel_time
  name: Michael To Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.michael_g7
  destination: zone.home
  scan_interval: 86400
